name: "[CHECK] PR - API"

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: records_db_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate Prisma client (identity)
        working-directory: packages/identity
        run: npx prisma generate
        env:
          IDENTITY_DB_URL: postgresql://admin:password123@localhost:5432/records_db_test
      - name: Generate Prisma client (medical-records)
        working-directory: packages/medical-records
        run: npx prisma generate
        env:
          MEDICAL_RECORDS_DB_URL: postgresql://admin:password123@localhost:5432/records_db_test
      - name: Quality Check
        run: yarn precommit:check